spring:
  application:
    name: crud-api

  datasource:
    url: jdbc:postgresql://localhost:5432/crud_api
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: true
    open-in-view: false

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE